---
buildToolImages:
  MBTJ21N18:
    dockerImage: devxci/mbtci-java21-node18

stages:
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ21N18"

  malwareScan:
    scan: false

  additionalTests:
    npmTests:
      run: false

  release:
    cfDeploy:
      strategy: "default"
      credential: "cf"
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com/"
      org: "8c98b2b0trial"
      space: "dev"
